version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "1883:1883"   # Port MQTT
      - "9001:9001"   # Port WebSocket
    volumes:
      - ${APP_DATA_DIR}/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${APP_DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${APP_DATA_DIR}/mosquitto/log:/mosquitto/log
    security_opt:
      - no-new-privileges:true
