version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "7575:80"
    volumes:
      - ${APP_DATA_DIR}/blackcandy.local:/etc/nginx/vhost.d/blackcandy.local:ro"
      - ${APP_DATA_DIR}/var/run/docker.sock:/tmp/docker.sock:ro"
      - ${APP_DATA_DIR}/media_data:/media_data" # Keep the path of media files in container the same as blackcandy container.

  app:
    image: ghcr.io/blackcandy-org/blackcandy:latest 
    volumes:
      - ${APP_DATA_DIR}/storage_data:/app/storage"
      - ${APP_DATA_DIR}/media_data:/media_data"
    environment:
      VIRTUAL_HOST: blackcandy.local
      MEDIA_PATH: /media_data
      NGINX_SENDFILE: "true" # Don't forget to set `NGINX_SENDFILE` environment variable to true to enable nginx sendfile.

