services:
  swingmusic:
    image: swingmusic
    container_name: swingmusic
    volumes:
      - ${APP_DATA_DIR}/music:/music
      - ${APP_DATA_DIR}/config:/config
    ports:
      - "1970:1970"
    restart: unless-stopped
