version: "3.8"
services:
  surfshark:
    image: ilteoood/docker-surfshark
    container_name: surfshark
    environment:
      - SURFSHARK_USER=${SURFSHARK_USER}
      - SURFSHARK_PASSWORD=${SURFSHARK_PASSWORD}
      - SURFSHARK_COUNTRY=it
      - SURFSHARK_CITY=mil
      - CONNECTION_TYPE=udp
      - LAN_NETWORK=192.168.0.0/24
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9091:9091
    dns:
      - 1.1.1.1
    networks:
      - umbrel_main_network
    restart: unless-stopped
  service_test:
    image: byrnedo/alpine-curl
    container_name: alpine
    command: -L 'https://ipinfo.io'
    depends_on:
      - surfshark
    network_mode: service:surfshark
    restart: always