version: '3.8'
services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        volumes:
            - ${APP_DATA_DIR}/data:/app/data
            - ${APP_DATA_DIR}/udev:/run/udev:ro
        ports:
            # Frontend port
            - 8082:8080
        environment:
            - TZ=Europe/Warsaw
        devices:
            # Make sure this matched your adapter location
            - port: tcp://10.0.1.16:6638
            - adapter: ember
