version: '3.9'
services:
    dumbdrop:
        image: abite3/dumbdrop:latest
        ports:
            - "3000:3001"
        volumes:
            - "${APP_DATA_DIR}/local_uploads:/app/uploads"
        environment:
            - DUMBDROP_PIN=123456
        