version: '3.9'
services:
    dumbdrop:
        image: abite3/dumbdrop:latest
        ports:
            - "7608:3000"
        volumes:
            - "${APP_DATA_DIR}/local_uploads:/app/uploads"
        environment:
            - DUMBDROP_PIN=${DUMBDROP_PIN}
#           - MAX_FILE_SIZE=2048
        