version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    network_mode: host
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "1880:1880"
    volumes:
      - ${APP_DATA_DIR}/data:/data
