version: '2'
services:
   nodered:
    image: drjp81/nodered:latest
    restart: unless-stopped
    container_name: nodered
    network_mode: host
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ${APP_DATA_DIR}/data:/data
