version: '2'
services:
  node-red:
    image: nodered/node-red:latest
    restart: always
    network_mode: host
    ports:
      - "1880:1880"  
    environment:
      - TZ=Europe/Amsterdam
      - DEBUG=NRCHKB:*
    volumes:
      - ${APP_DATA_DIR}/data:/data
