version: '3'  
services:  
  matter-server:  
    container_name: matter-server 
    image: ghcr.io/home-assistant-libs/python-matter-server:stable 
    restart: unless-stopped  
    security_opt:  
      - apparmor=unconfined  
    volumes:  
      - ${APP_DATA_DIR}/data:/data  
      - ${APP_DATA_DIR}/run/dbus:/run/dbus:ro  
    network_mode: host
