version: '3'

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "853:853/tcp"
      - "3000:3000/tcp"
      - "80:8088/tcp"
      - "6443:443/tcp"
    volumes:
      - ./data:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
