version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ${APP_DATA_DIR}/data:/opt/app/backend/data
      - ${APP_DATA_DIR}/data/images:/opt/app/frontend/public/img
  
