version: "3.7"

services:
  aiptv:
    image: monis256/aiptv:latest
    container_name: Aiptv
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "51976:5000"
    environment:
      DB_PORT: "5433" # opcjonalnie
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${APP_DATA_DIR}/data/aiptv/:/aiptv/data/"
    #devices: # opcjonalnie
    #  - "/dev/dri:/dev/dri"
