version: "3.8"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: marcias-puter_server_1
      APP_PORT: 4100
      TZ: Europe/Warsaw
   
    volumes:
      - ${APP_DATA_DIR}/puter/config:/etc/puter
      - ${APP_DATA_DIR}/puter/data:/var/puter
      
  server:
    image: ghcr.io/heyputer/puter:latest
    user: "1000:1000"
    init: true
    pull_policy: always
    restart: unless-stopped


