version: "3.8"
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    # build: ./
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
       TZ: Europe/Warsaw
      # CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/puter/config:/etc/puter
      - ${APP_DATA_DIR}/puter/data:/var/puter
    # healthcheck:
     # test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1
     # interval: 30s
     # timeout: 3s
     # retries: 3
     # start_period: 30s





