version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${APP_DATA_DIR}/mosquitto:/etc/mosquitto
      - ${APP_DATA_DIR}/mosquitto.conf:/mosquitto/config/mosquitto.conf


