version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Warsaw
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_6c007fbc91e5ed11b51e606262c613ac-if00-port0:/dev/ttyACM0
