channels-dvr:
  image: fancybits/channels-dvr:latest
  container_name: channels-dvr
  network_mode: host
  ports:
    - "8089:8089"
  restart: on-failure:10
  devices:
    - /dev/dri:/dev/dri
  volumes:
    - /mnt/disk/dvr/config:/channels-dvr
    - /mnt/disk/dvr/recordings:/shares/DVR
